#!/bin/bash

SUFFIX="flac"
TEMPORARY_SPLIT_FILE_PREFIX="split_track_"
IS_RECURSIVE=0
IS_DELETE_AFTER_CONVERT=0
IS_DELETE_CUE_FILE=0

function convert_flac2alac { 
    DIR="$1"

    if [ $IS_RECURSIVE -eq 1 ]; then  
	for folder in "$DIR"/*;
        do
	    if [ -d "$folder" ] ; then
	       convert_flac2alac "$folder"
	    fi
        done
    fi

    #If there is a cue file and s "big" flac then try to 
    #split it into separate  tracks
    for cueFile in "$DIR"/*.cue
    do
        flacFileName="`basename "$cueFile" .cue`.$SUFFIX"

        if [ -f "$DIR"/"$flacFileName" ]; then  	      

            #Cue file and corresonded flac were found
	    #so we need to split it on small flac files in format split_track_number_title.flac
            cuebreakpoints "$cueFile" | shnsplit -o flac -a "$DIR"/"$TEMPORARY_SPLIT_FILE_PREFIX" -f "$cueFile" -t "%n-%t" "$DIR"/"$flacFileName"

            #Move tags from cue file to flacs
            cuetag "$cueFile" "$DIR"/"$TEMPORARY_SPLIT_FILE_PREFIX"*."$SUFFIX"

            #If delete parameter was found then remove "big" flac file
	    if [ $IS_DELETE_AFTER_CONVERT -eq 1 ]; then  
	        rm -v "$DIR"/"$flacFileName"
            fi   

            #delete corresponded cue file if necessary
            if [ $IS_DELETE_CUE_FILE -eq 1 ]; then  
	        rm -v "$cueFile"
            fi   

        fi
    done

    #Now we neeed to convert each track to alac
    #preserving tags data
    for i in "$DIR"/"$TEMPORARY_SPLIT_FILE_PREFIX"*.$SUFFIX
    do
        if [ -f "$i" ]; then  	
		 ffmpeg  -i "$i" \
       	         -metadata title="$(metaflac --show-tag=TITLE "$i" | sed 's/title=//gI')" \
                 -metadata author="$(metaflac --show-tag=ARTIST "$i" | sed 's/artist=//gI')" \
                 -metadata album="$(metaflac --show-tag=ALBUM "$i" | sed 's/album=//gI')" \
                 -metadata year="$(metaflac --show-tag=DATE "$i" | sed 's/date=//gI')" \
                 -metadata track="$(metaflac --show-tag=TRACKNUMBER "$i" | sed 's/tracknumber=//gI')" \
                 -metadata genre="$(metaflac --show-tag=GENRE "$i" | sed 's/genre=//gI')" \
                 -acodec alac "$i".m4a

            #Delete flacs if necessary
            if [ $IS_DELETE_AFTER_CONVERT -eq 1 ]; then  
	        rm -v "$i"
            fi 
	fi
    done
}

for parameter in "$@"; do
	if [ "$parameter" = "-r" ]; then
		IS_RECURSIVE=1
	fi
	if [ "$parameter" = "-d" ]; then
		IS_DELETE_AFTER_CONVERT=1
	fi
	if [ "$parameter" = "--delete_cue" ]; then
		IS_DELETE_CUE_FILE=1
	fi
	if [ -d "$parameter" ]; then
		convert_flac2alac "$parameter"
	fi
done
